language: node_js
node_js: lts/*

addons:
  chrome: stable

cache:
  directories:
    - ~/.rvm/gems
    - node_modules

install:
  - npm install
  - bundle install

script:
  - npm run build
  - npm run preprod
  - npm run test
